<?php
/**
 * This file is part of the French language pack for the
 * phpBB forum software.
 *
 * @copyright (c) phpBB Limited <https://www.phpbb.com>
 * @copyright (c) Qiaeru <https://www.qiae.ru>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * For more information about the language pack, please visit
 * https://www.phpbb.com/customise/db/translation/french/
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = [];
}

$lang = array_merge($lang, [
	'HELP_BBCODE_BLOCK_IMAGES' => 'Affichage d’images dans les messages',
	'HELP_BBCODE_BLOCK_INTRO'  => 'Introduction',
	'HELP_BBCODE_BLOCK_LINKS'  => 'Insertion de liens',
	'HELP_BBCODE_BLOCK_LISTS'  => 'Création de listes',
	'HELP_BBCODE_BLOCK_OTHERS' => 'Divers',
	'HELP_BBCODE_BLOCK_QUOTES' => 'Citation et données de largeur fixe',
	'HELP_BBCODE_BLOCK_TEXT'   => 'Mise en forme du texte',

	'HELP_BBCODE_IMAGES_ATTACHMENT_ANSWER'   => 'Les pièces jointes peuvent désormais être envoyées dans les messages via le BBCode « <strong>[attachment=][/attachment]</strong> », si la fonctionnalité est activée par les administrateurs et si vous en avez la permission. Pour envoyer une pièce jointe en ligne, sélectionnez-la depuis la liste déroulante de la page de rédaction et cliquez sur le bouton correspondant.',
	'HELP_BBCODE_IMAGES_ATTACHMENT_QUESTION' => 'Envoyer une pièce jointe dans un message',
	'HELP_BBCODE_IMAGES_BASIC_ANSWER'        => 'Le BBCode de phpBB inclut une balise pour insérer des images dans vos messages. Deux choses sont à garder à l’esprit : l’excès d’images dans un message est mal vu de la plupart des utilisateurs, et l’image que vous voulez afficher doit déjà être disponible en ligne (elle ne peut pas être uniquement sur votre ordinateur, sauf si celui-ci est un serveur web). Pour afficher une image, placez le lien vers l’image entre les balises « <strong>[img][/img]</strong> ». Par exemple :<br><br><strong>[img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img]</strong><br><br>Comme indiqué dans la section précédente, vous pouvez aussi imbriquer une image dans une balise « <strong>[url][/url]</strong> ». Par exemple :<br><br><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img][/url]</strong><br><br>Donnera :<br><br><a href="https://www.phpbb.com/"><img src="https://www.phpbb.com/theme/images/logos/blue/160x52.png" alt="" /></a>',
	'HELP_BBCODE_IMAGES_BASIC_QUESTION'      => 'Ajouter une image à un message',

	'HELP_BBCODE_INTRO_BBCODE_ANSWER'   => 'Le BBCode est une variante du HTML. Vous pouvez l’utiliser dans vos messages si la fonctionnalité a été autorisée par un administrateur. Vous pouvez aussi le désactiver pour chaque message depuis le formulaire de rédaction. La syntaxe du BBCode est proche du HTML : les balises sont entourées de crochets « [ » et « ] » au lieu des chevrons « &lt; » et « &gt; », et il offre un bon contrôle sur la mise en forme. Selon le style utilisé, une interface cliquable est disponible juste au-dessus du formulaire de rédaction pour insérer facilement du BBCode. Le guide ci-dessous fournit plus de détails.',
	'HELP_BBCODE_INTRO_BBCODE_QUESTION' => 'Qu’est-ce que le BBCode ?',

	'HELP_BBCODE_LINKS_BASIC_ANSWER'   => 'Le BBCode de phpBB propose plusieurs façons de créer des liens.<ul><li>La première utilise la balise « <strong>[url=][/url]</strong> » : ce qui suit le signe égal « = » devient la cible du lien, et le contenu de la balise en devient le texte. Par exemple, pour créer un lien vers phpBB.com :<br><br><strong>[url=https://www.phpbb.com/]</strong>Visitez phpBB.com !<strong>[/url]</strong><br><br>Donnera : <a href="https://www.phpbb.com/">Visitez phpBB.com !</a> Le lien peut s’ouvrir dans la même fenêtre ou dans une nouvelle, selon les préférences du navigateur.</li><li>Pour afficher simplement l’URL, utilisez :<br><br><strong>[url]</strong>https://www.phpbb.com/<strong>[/url]</strong><br><br>Donnera : <a href="https://www.phpbb.com/">https://www.phpbb.com/</a></li><li>phpBB propose également les <i>liens magiques</i> : tout lien y est automatiquement transformé en lien valide, sans balises ni « https:// ». Par exemple, écrire « www.phpbb.com » dans votre message produit automatiquement « <a href="https://www.phpbb.com/">www.phpbb.com</a> » à l’affichage.</li><li>Idem pour les adresses e-mail. Vous pouvez utiliser une balise explicite, par exemple :<br><br><strong>[email]</strong>inconnu@domaine.adr<strong>[/email]</strong><br><br>Donnera : <a href="mailto:inconnu@domaine.adr">inconnu@domaine.adr</a>. Vous pouvez aussi simplement écrire « inconnu@domaine.adr », la conversion sera automatique à l’affichage.</li></ul>Comme pour toute balise BBCode, vous pouvez imbriquer un lien autour d’autres balises (« <strong>[img][/img]</strong> », voir la question suivante, « <strong>[b][/b]</strong> », etc.). Veillez à respecter l’ordre d’ouverture et de fermeture. Par exemple :<br><br><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/url][/img]</strong><br><br>n’est <span style="text-decoration: underline">pas</span> correct et peut entraîner la suppression de votre message. Soyez vigilant.',
	'HELP_BBCODE_LINKS_BASIC_QUESTION' => 'Insérer un lien vers un site web',

	'HELP_BBCODE_LISTS_ORDERER_ANSWER'     => 'Le second type de liste, la liste ordonnée, vous donne le contrôle sur le préfixe de chaque article. Utilisez les balises « <strong>[list=1][/list]</strong> » pour une liste numérotée, ou « <strong>[list=a][/list]</strong> » pour une liste alphabétique. Comme pour la liste non ordonnée, chaque article se définit avec la balise « <strong>[*]</strong> ». Par exemple :<br><br><strong>[list=1]</strong><br><strong>[*]</strong>Faire les courses<br><strong>[*]</strong>Acheter un nouvel ordinateur<br><strong>[*]</strong>Râler quand l’ordinateur plante<br><strong>[/list]</strong><br><br>Donnera :<ol style="list-style-type: decimal;"><li>Faire les courses</li><li>Acheter un nouvel ordinateur</li><li>Râler quand l’ordinateur plante</li></ol>Pour une liste alphabétique, utilisez :<br><br><strong>[list=a]</strong><br><strong>[*]</strong>Première réponse possible<br><strong>[*]</strong>Deuxième réponse possible<br><strong>[*]</strong>Troisième réponse possible<br><strong>[/list]</strong><br><br>Donnera :<ol style="list-style-type: lower-alpha"><li>Première réponse possible</li><li>Deuxième réponse possible</li><li>Troisième réponse possible</li></ol><br><strong>[list=A]</strong><br><strong>[*]</strong>Première réponse possible<br><strong>[*]</strong>Deuxième réponse possible<br><strong>[*]</strong>Troisième réponse possible<br><strong>[/list]</strong><br><br>Donnera :<ol style="list-style-type: upper-alpha"><li>Première réponse possible</li><li>Deuxième réponse possible</li><li>Troisième réponse possible</li></ol><br><strong>[list=i]</strong><br><strong>[*]</strong>Première réponse possible<br><strong>[*]</strong>Deuxième réponse possible<br><strong>[*]</strong>Troisième réponse possible<br><strong>[/list]</strong><br><br>Donnera :<ol style="list-style-type: lower-roman"><li>Première réponse possible</li><li>Deuxième réponse possible</li><li>Troisième réponse possible</li></ol><br><strong>[list=I]</strong><br><strong>[*]</strong>Première réponse possible<br><strong>[*]</strong>Deuxième réponse possible<br><strong>[*]</strong>Troisième réponse possible<br><strong>[/list]</strong><br><br>Donnera :<ol style="list-style-type: upper-roman"><li>Première réponse possible</li><li>Deuxième réponse possible</li><li>Troisième réponse possible</li></ol>',
	'HELP_BBCODE_LISTS_ORDERER_QUESTION'   => 'Créer une liste ordonnée',
	'HELP_BBCODE_LISTS_UNORDERER_ANSWER'   => 'Le BBCode prend en charge deux types de listes : ordonnée et non ordonnée. Elles sont quasi identiques à leurs équivalents HTML. Une liste non ordonnée affiche chaque élément à la suite, précédé d’une puce. Pour la créer, utilisez les balises « <strong>[list][/list]</strong> » et définissez chaque élément avec « <strong>[*]</strong> ». Par exemple, pour lister vos couleurs préférées :<br><br><strong>[list]</strong><br><strong>[*]</strong>Rouge<br><strong>[*]</strong>Bleu<br><strong>[*]</strong>Jaune<br><strong>[/list]</strong><br><br>Donnera la liste :<ul><li>Rouge</li><li>Bleu</li><li>Jaune</li></ul><br>Vous pouvez aussi créer une liste à puces avec « <strong>[list=disc][/list]</strong> », « <strong>[list=circle][/list]</strong> » ou « <strong>[list=square][/list]</strong> ».',
	'HELP_BBCODE_LISTS_UNORDERER_QUESTION' => 'Créer une liste non ordonnée',

	'HELP_BBCODE_OTHERS_CUSTOM_ANSWER'   => 'Si vous êtes administrateur du forum et que vous avez les permissions nécessaires, vous pouvez ajouter d’autres BBCodes dans la section « Personnaliser les BBCodes ».',
	'HELP_BBCODE_OTHERS_CUSTOM_QUESTION' => 'Puis-je ajouter mes propres balises ?',

	'HELP_BBCODE_QUOTES_CODE_ANSWER'   => 'Pour insérer un fragment de code ou un texte à largeur fixe (comme avec la police « Courier »), entourez-le des balises « <strong>[code][/code]</strong> ». Par exemple :<br><br><strong>[code]</strong>echo &quot;Ceci est un fragment de code&quot;;<strong>[/code]</strong><br><br>Toutes les balises de mise en forme placées entre « <strong>[code][/code]</strong> » sont conservées telles quelles à l’affichage.',
	'HELP_BBCODE_QUOTES_CODE_QUESTION' => 'Mettre en forme du code ou un texte à largeur fixe',
	'HELP_BBCODE_QUOTES_TEXT_ANSWER'   => 'Il existe deux façons de citer un texte, avec ou sans référence :<ul><li>Lorsque vous utilisez la fonction de citation pour répondre à un message, le texte ajouté à la fenêtre de rédaction est encadré par les balises « <strong>[quote=&quot;&quot;][/quote]</strong> ». Cette méthode permet de citer une personne ou autre référence à commenter. Par exemple, pour citer un texte de M.\xa0Blobby, écrivez :<br><br><strong>[quote=&quot;M. Blobby&quot;]</strong>Le texte de M.\xa0Blobby ici<strong>[/quote]</strong><br><br>Le texte « M.\xa0Blobby a écrit » sera ajouté automatiquement avant la citation. Vous devez <strong>impérativement</strong> entourer le nom cité de guillemets anglais « &quot; &quot; » ; ils sont obligatoires.</li><li>La seconde méthode permet de citer anonymement : entourez simplement le texte des balises « <strong>[quote][/quote]</strong> ». À l’affichage, le texte apparaîtra dans un bloc de citation.</li></ul>',
	'HELP_BBCODE_QUOTES_TEXT_QUESTION' => 'Citer un texte dans une réponse',

	'HELP_BBCODE_TEXT_BASIC_ANSWER'     => 'Le BBCode inclut des balises pour modifier rapidement le style de votre texte. Plusieurs options sont possibles :<ul><li>Pour mettre du texte en gras, encadrez-le des balises « <strong>[b][/b]</strong> ». Par exemple :<br><br><strong>[b]</strong>Salut<strong>[/b]</strong><br><br>Donnera : <strong>Salut</strong></li><li>Pour souligner du texte, utilisez les balises « <strong>[u][/u]</strong> ». Par exemple :<br><br><strong>[u]</strong>Bonjour<strong>[/u]</strong><br><br>Donnera : <span style="text-decoration: underline">Bonjour</span></li><li>Pour mettre du texte en italique, utilisez les balises « <strong>[i][/i]</strong> ». Par exemple :<br><br>C’est <strong>[i]</strong>super !<strong>[/i]</strong><br><br>Donnera : C’est <i>super !</i></li></ul>',
	'HELP_BBCODE_TEXT_BASIC_QUESTION'   => 'Comment mettre du texte en gras, en italique ou souligné ?',
	'HELP_BBCODE_TEXT_COLOR_ANSWER'     => 'Pour modifier la taille ou la couleur du texte, utilisez les balises ci-dessous. Le rendu final dépend du navigateur web et du système d’exploitation :<ul><li>Pour colorer une partie du texte, encadrez-la des balises « <strong>[color=][/color]</strong> ». Vous pouvez utiliser un nom de couleur reconnu (« red », « blue », « yellow »…) ou un code hexadécimal (« #FFFFFF », « #000000 »…). Par exemple, pour mettre du texte en rouge :<br><br><strong>[color=red]</strong>Salut !<strong>[/color]</strong><br><br>Ou :<br><br><strong>[color=#FF0000]</strong>Salut !<strong>[/color]</strong><br><br>Donnera dans les deux cas : <span style="color:red">Salut !</span></li><li>Pour modifier la taille, utilisez les balises « <strong>[size=][/size]</strong> ». Le format dépend du style sélectionné, mais le format recommandé est une valeur numérique en pourcentage, de 50 (minuscule) à 200 (énorme). Par exemple :<br><br><strong>[size=30]</strong>MINUSCULE<strong>[/size]</strong><br><br>Donnera : <span style="font-size:30%;">MINUSCULE</span><br><br>Tandis que :<br><br><strong>[size=200]</strong>ÉNORME !<strong>[/size]</strong><br><br>Donnera : <span style="font-size:200%;">ÉNORME !</span></li></ul>',
	'HELP_BBCODE_TEXT_COLOR_QUESTION'   => 'Comment modifier la taille ou la couleur du texte ?',
	'HELP_BBCODE_TEXT_COMBINE_ANSWER'   => 'Bien sûr ! Par exemple, pour attirer l’attention, vous pouvez écrire :<br><br><strong>[size=200][color=red][b]</strong>REGARDEZ-MOI !<strong>[/b][/color][/size]</strong><br><br>Donnera : <span style="color:red;font-size:200%;"><strong>REGARDEZ-MOI !</strong></span><br><br>Évitez toutefois ce genre de mise en forme à outrance. Pensez à fermer les balises correctement et dans le bon ordre. Ce qui suit est incorrect :<br><br><strong>[b][u]</strong>Ceci est incorrect<strong>[/b][/u]</strong>',
	'HELP_BBCODE_TEXT_COMBINE_QUESTION' => 'Puis-je combiner des balises de mise en forme ?',
]);
